danihodovic/celery-exporter

README.md
src/cli.py
src/exporter.py
src/help.py
src/test_cli.py

Hi Dani,
Thanks for your great library! I’d like to contribute one simple metric that I felt was missing. It’s simple Histogram which tracks runtime that celery sends with task-succeeded event. I also added one optional CLI argument, ‘buckets’, for histogram buckets initialization. I hope you find it useful. Looking forward to your comments if something’s off in the code.

Added celery_task_runtime metric

---

README.md

Fix `celery_task_runtime` metric's name in README

Fix celery_task_runtime metric's name in README

---

poetry.lock
pyproject.toml
src/exporter.py

Thanks for this exporter!
this PR solves #47
it goes through all counters and increases the not-matched counters by zero so they are populated with the corresponding labels and an unchanged value (0 if unset).
to make celery-exporter work i had to remove the git-dependency to celery.
That solves #71
Is the "allow-heartbeats-in-tests" used somewhere?
and then there is this: https://github.com/pallets/markupsafe/issues/282
so i pinned the version in pyproject.toml

Set all counter values to zero on start

---

.gitignore
Dockerfile.pyinstaller
Taskfile.yml
pyproject.toml

Uses a base image with Ubuntu:16.04 which should be compatible with
distros that have an older version of glibc.

Use docker container for stable pyinstaller builds

---

poetry.lock

- This version includes: https://github.com/celery/kombu/pull/1495 which fixes an issue where pubsub clients would not work with messages that include the global_keyprefix.

Needing to bump Kombu to 5.2.4.

---

README.md
conftest.py
src/cli.py
src/exporter.py
src/test_cli.py

When communicating with redis that has been configured to receive prefixed keys from workers via either ye-old CELERY_BROKER_TRANSPORT_OPTIONS or the newer broker_transport_options with the "global_keyprefix" option,
celery-exporter does not properly subscribe to those keys, events will not be seen and thus no metrics updated.
This PR adds the ability to specify one or more `--broker_transport_option` on the cli that will be honored by celery-exporter and the appropriate celery config updated.
i.e.  
```
python /app/cli.py --broker redis://my_redis:6379 \
--broker_transport_option global_keyprefix=aab \
--broker_transport_option visibility_timeout=10800
...
```

Adding support for Celery broker_transport_options.

---

README.md
conftest.py
src/cli.py
src/exporter.py
src/test_cli.py

It is intended as a broker exception retry interval and is specified as number of seconds.
By default, if there is an exception while communicating with the broker, celery-exporter exits with a stack trace.
It is not uncommon to temporarily lose connectivity to redis for a very short amount of time. With the default behavior, the
exporter will need a restart thus losing all accumulated metrics.
With the new --retry-interval options specified, one can specify and optional retry interval (i.e. 5 seconds) and
celery-exporter will restart the celery EventReceiver for that broker.
The default is 0, (i.e. do not retry) in order to keep compatibility (and expected behavior) with the current
celery-exporter.

Added support for the --retry-interval command line option.

---

cli.py
src/cli.py

Adds support for using environment variables to configure the exporter. Useful when running outside of Kubernetes, where secrets are handled .. chaotically. Example for AWS Fargate:
```
secrets = [
{
name      = "RABBIT_USER"
valueFrom = "arn:aws:ssm:user-parameter"
},
{
name      = "RABBIT_PASSWORD"
valueFrom = "arn:aws:ssm:password"
}
]
environment = [
{
name = "BROKER_URL"
value = "amqps://${RABBIT_USER}:${RABBIT_PASSWORD}@broker-id.mq.amazonaws.com:5671/vhost"
},
{
name = "RETRY_INTERVAL"
value = "15"
}
]
```

support for environment variables

---

src/test_cli.py

Add tests for celery_task_sent_total
If you're working with async test - just add more `sleep`, usually it helps :D 
I think there's a problem with daemon - it `threading.Thread.start` waits until the thread is ready, not when the app is healthy and connected to a broker - so we missed `task-sent` events.
Fixes https://github.com/danihodovic/celery-exporter/issues/121

Add tests for celery_task_sent_total

---

README.md
charts/celery-exporter/Chart.yaml
charts/celery-exporter/templates/servicemonitor.yaml
charts/celery-exporter/values.yaml
cli.py

`CELERY_EXPORTER` as a prefix collides with default Kubernetes environment variables as `CELERY_EXPORTER_PORT` and others used for service discovery. 
https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

fix: Change env var prefix and change service monitor port

---

conftest.py
pytest.ini
src/exporter.py
src/test_cli.py
src/test_metrics.py

The exporter are using original `hostname` value from celery's events data. 
Celery uses [anon_nodename](https://docs.celeryq.dev/en/stable/internals/reference/celery.utils.nodenames.html?highlight=anon_nodename#celery.utils.nodenames.anon_nodename) to get the value and the value has format "prefix@hostname".
The prefix part is different depending on type of a process:
1. For workers the prefix is a worker's name, e.g., `worker1@allburov`
2. For senders the prefix has a format `genPID@hostname` where PID is Process ID, e.g., `gen1231234@allburov`
The part with PID has high cardinality and it leads to too much metrics in Prometheus (as described in  https://github.com/danihodovic/celery-exporter/issues/116)
[Prometheus suggests](https://prometheus.io/docs/practices/naming/):
>CAUTION: …

Remove a  prefix `gen4312` from a hostname

---

.pre-commit-config.yaml
README.md
poetry.lock
pyproject.toml

Add pre-commit hooks, use them in CI.
It'll remove annoying scenario where you have to run three commands before the commit manually or (as I did) look at failed CI build to find out what linters the project uses.
Pre-commit always runs checks before the commit - it takes a few seconds, but work so great!
I added a little section in README.md about "Development" - please feel give a feedback about it and change the language if it's needed!
Fixes #138

Add pre-commit hooks

---

.dockerignore

[The last image](https://hub.docker.com/layers/celery-exporter/danihodovic/celery-exporter/0.5.2/images/sha256-1a042ba614f84c7ff8e04b3e6289abb0681bc5f1860e07dc0c444a323464c5ab?context=explore)'s step `COPY . /app/ # buildkit` has size 87.1 MB
I found few unnecessary folders in the `/app/` that we could ignore to reduce an image size 
```
root@4d306fc2ebb2:/app# du -h | grep M
36M     ./build/celery-exporter
36M     ./build
5.1M    ./.git/objects
5.7M    ./.git
1.6M    ./.mypy_cache/3.9/cryptography/hazmat
2.2M    ./.mypy_cache/3.9/cryptography
1.3M    ./.mypy_cache/3.9/jinja2
2.3M    ./.mypy_cache/3.9/_pytest
2.0M    ./.mypy_cache/3.9/werkzeug
24M     ./.mypy_cache/3.9
24M     ./.mypy_cache
26M     ./dist
```

Ignore big directories in docker

---

src/exporter.py

fixes #143 
I'm not sure if it's a perfect long-term solution, but right now kombu throws ChannelError on queue_declare only if _has_queue is false. So, we can safely ignore ChannelErrors from redis and won't miss any other exception https://github.com/celery/kombu/blob/7516daf7a774dd9671d16c475c6ac266de977a0a/kombu/transport/virtual/base.py#L521

don't log exceptions for ChannelErrors from redis

---

src/cli.py
src/exporter.py

Reference: https://github.com/danihodovic/celery-exporter/issues/153
Problem: celery-exporter expects default Celery configuration.
Proposal: New custom-config parameter allowing configuration load from a module.

feat: Add custom accept content configuration

---

.coveragerc
.github/workflows/ci.yml
.pylintrc
README.md
conftest.py
docker-compose.yml
poetry.lock
src/test_cli.py
src/test_http_server.py
src/test_metrics.py

Adds tests for Redis and RabbitMQ. Specify the pytest parameter
--broker=redis to run the test suite for Redis and --broker=redis for
RabbitMQ.

test: add tests for Redis and RabbitMQ

---

.coveragerc
README.md
src/exporter.py
src/test_cli.py

Better error handling to detect the transport.
```python
if isinstance(connection.default_channel.client, Redis):
```
The above fails when the transport is not Redis with an AttributeError as the .client attribute is not set on the default_channel.

fix: fixups for queue length

---

Dockerfile

I think that 90+ critical CVE in base image is too much :-)

Update base python/debian image and optimize image size

---

pyproject.toml

The pyproject.toml file had both old-style and new-style dev dependency grouping. Updated to just use the new poetry style.
Should check that this does not impact CI and builds.
If you don't wish to review the `poetry.lock` file. I'd be happy to re-submit with just the `pyproject.toml` file changes. Then you could perform `poetry lock --no-update` on your own.

Using the new poetry dev group

---

charts/celery-exporter/Chart.yaml
pyproject.toml
src/exporter.py
src/test_cli.py

For celery_queue_length the queue name label is `queue_name`, unify it across all metrics. Also, bump to 0.7.2, just publish a docker image

fix: Unify queue name label

---

src/exporter.py

Implements #220.
This turned out to be much easier than I expected. Celery seems to just handle all the details of the Sentinel connection for us automatically.
Tested with a basic docker-compose stack running sentinel, where I killed the workers and then queued tasks. All the other metrics seemed fine, but the queue size correctly tracked the number of tasks I added as expected:
```
❯ curl localhost:9808/metrics -s | rg celery_queue
celery_queue_length{queue_name="default"} 1.0
```
Let me know if there's some other testing or something I should do here, or if there's something I'm missing given how surprisingly easy this was.

support celery_queue_size metric for sentinels

---

charts/celery-exporter/README.md
charts/celery-exporter/templates/deployment.yaml
charts/celery-exporter/values.yaml

Added "Liveness and readiness probe timeout values" in values.yaml - To be able to change the timeout values.
```
livenessProbe: {}
readinessProbe: {}
```

Add Liveness and readiness probe timeout values

---

conftest.py
src/cli.py
src/exporter.py
src/test_metrics.py

Fixes #228.
In that issue a worker timeout was discussed but it was believed that a separate thread would be needed to implement it. In this PR I take the approach of removing the expired workers on the Prometheus scrape avoiding the need for an additional thread.
I have added a cli option to specify the time frame with a default of 5 minutes. I've also added the ability for users to stick to the old functionality by turning this parameter to 0.

Add timeout to workers to correct for force killed workers

---

src/exporter.py

Currently queue length tracking is disabled for connection strings that use the `amqps` (amqp with ssl) transport. 
This PR adds "amqps" to the list of acceptable transports for queue length tracking (since it's allowed for amqp).

Support amqps transport for queue length tracking

---

celery-mixin/dashboards/celery-tasks-overview.libsonnet
celery-mixin/dashboards_out/celery-tasks-overview.json

Too many bucket queries == slow loads

fix: Remove p99.9 queries from overviews

---

README.md
src/exporter.py
src/test_cli.py

This PR extends the `celery_active_consumer_count` metric beyond the currently supported brokers by using the Inspect object's `stat` method, and using the number of worker thread PID's returned as the amount of consumers on that worker. It then cross references that with the queues that worker is consuming from to create an amount of threads that could be working from that queue.
I'm not 100% sure of the terminology used. It could be that "active consumers" are intended to be the amount of workers, rather than the total amount of threads, or it could be that "active" is intended to mean the amount of threads currently working on tasks from that queue. I haven't been able to find good documentation on that in the celery, kombu, RabbitMQ, or Qpid documentation.

Use Inspect object to get consumer count in a broker agnostic way

---

src/exporter.py

If any other Celery concurrency method is used other than `prefork` the `pool` `processes` information might not be available, resulting in a failure when scraping metrics. This PR makes sure the processes are only counted for `prefork`.

Make exporter work with eventlet concurrency

---

conftest.py
src/cli.py
src/exporter.py
src/test_cli.py

We are running celery-exporter in a kubernetes environment and using the metrics it provides to scale the number of workers. Sometimes we scale the number of workers down to zero automatically e.g test environments out of office hours for instance.
When there are no workers, if celery-exporter stops for any reason (e.g. kubernetes moves it to a different node), celery-exporter stops reporting metrics for the queues as it has no way of knowing what the queues are. In our case this means we can never automatically scale back up as the metrics are missing.
As we know all of the queues we wish to be following in advance, being able to tell celery-exporter all the queues we wish to have metrics for is a useful feature.
Implementation is straight forward as there is already the `queue_cache` to …

Allow queue cache to be initialized from the command line

---

celery-mixin/alerts/alerts.libsonnet
celery-mixin/prometheus-alerts.yaml
celery-mixin/tests.yaml

fix(mixin): Fix alert syntax

---

src/cli.py
src/exporter.py

For setting a custom prefix for all metrics.

feat: metric-prefix configuration

---

poetry.lock
pyproject.toml

Per #295, this updates vulnerable versions of pyinstaller and certifi.

fix: update deps with cves

---

Dockerfile.pyinstaller
buildInstaller.sh

This is required for work with rabbitmq.
Should fix #119 - regarding the last comments.

Added kombu.transport.pyamqp import to pyinstaller

---

Dockerfile

Want to ensure that containers running in my cluster aren't running as root. Creating a new user in the container `exporter` and changing the image to run with that user.

Build docker image to run with non root user

---

src/exporter.py
src/test_metrics.py

celery-exporter has this [feature](https://github.com/danihodovic/celery-exporter/pull/248) to purge ofline worker metrics which default to 10 minutes. So any worker that is offline for more than 10 minutes, the metrics of which will be purged
Now if celery workers is configured to use PST timezone (which is 7 hours behind UTC) or any other timezone that is not UTC, in such cases celery-exporter (running in UTC tz) considered live workers also to be offline because of this offset and this causes a continuous loop of live worker metrics to be purged and so we get inconsistent metrics.
Temp solution is to set `CE_WORKER_TIMEOUT` and `CE_PURGE_OFFLINE_WORKER_METRICS` to 7hrs + 10mins ahead

fix: Use event timestamp based on utcoffset

---

celery-mixin/config.libsonnet
celery-mixin/dashboards_out/celery-tasks-by-task.json
celery-mixin/dashboards_out/celery-tasks-overview.json

When deploying kube-prometheus and using PodMonitors the resulting job
name is "<namespace>/celery-exporter". This job name fails the regex
filter applied in the Grafana dashboard.

fix: celerySelector filter

---

.github/workflows/push-image-ghcr.yml

If there is a new tag created, github actions builds for multiarch (including ARM) and pushes to GHCR.
Closes:
- https://github.com/danihodovic/celery-exporter/issues/171
Probably closes:
- https://github.com/danihodovic/celery-exporter/issues/35

Automatically push to ghcr and build for ARM

---

conftest.py
src/cli.py
src/exporter.py
src/test_cli.py

Example: we have application with different environments, each having its own exporter. We want to distinguish metrics by environment by label, not by metric prefix. So we need to provide exporter with an ability to attach custom labels to metrics.
Implemented as cli arg `--static-label`, that can be provided multiple times in format `--static-label key=value`
Example:  `python cli.py --broker-url=redis://127.0.0.1:6379 --static-label application=my-application-name --static-label environment=staging`
Here is the result:
Code changes: 
- New cli arg
- In the code where metrics are defined, there are `*self.static_label_keys` at the end to unpack provided static labels names
- In the code where we provide labels for metrics now there are `**self.static_label`, which unpack static labels …

feat: Ability to add labels with constant values

---

README.md

added space that allows that command to be pasted directly

fix: typo error in README.md
